import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Sidebar from "@/components/layout/Sidebar";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-screen flex flex-col ">
        <div className="grid grid-cols-12 h-screen">
          <Sidebar />
          <div className="col-span-9 h-screen flex flex-col text-typo">
            <Navbar />
            <main className="flex-1 relative p-4">
              <Image
                src="/images/chat-bg.webp"
                alt="chat-bg-image"
                fill
                className="object-fill -z-1"
              />

              {children}
            </main>
            <div><Footer/></div>
          </div>
        </div>
      </body>
    </html>
  );
}
