import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";
import CategoryBar from "./components/CategoryBar";
import VideoList from "./components/styles/VideoList";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "YouTube Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="h-full flex flex-col">
        {/* Fixed Navbar */}
        <Navbar />

        <div className="flex">
          {/* Fixed Sidebar */}
          <aside className="w-20 fixed top-15 left-0 h-full overflow-y-auto">
            <Sidebar />
          </aside>

          {/* Main Content */}
          <main className="ml-20 mt-16 p-4 h-[calc(100vh-4rem)] overflow-y-auto">
            <CategoryBar />
            <VideoList />
            {/* {children} */}
          </main>
        </div>
      </body>
    </html>
  );
}
