import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Sidebar from "@/components/layout/Sidebar";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="h-screen flex">
        <Sidebar />

        <div className="flex-1 text-typo h-full flex flex-col">
          <Navbar />
          <main className="flex-1 relative p-4 overflow-auto h-full bg-[url('/images/chat-bg.webp')] bg-cover">

            {/* <Image
              src="/images/chat-bg.webp"
              alt="chat-bg-image"
              fill
              className="object-cover -z-1"
              quality={100}
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              loading="eager"
            /> */}


            {children}
          </main>
          <div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
